import { STORAGE_PREFIX, DEFAULT_PROTECTED_PATHS, DEFAULT_TIMEOUT_SECONDS } from "../constants";

export interface DeviceLocalSettings {
  schemaVersion: number;
  /** Master switch for this device; never synced through the vault. */
  enabledOnThisDevice: boolean;
  termuxIntegrationEnabled: boolean;
  /** Informational hint of the repo path as seen from Termux (the runner config owns the truth). */
  repoPathHint: string;
  /** Pairing token generated by the Termux installer and pasted here. */
  authToken: string;
  /**
   * Which Termux profile this vault is paired with (runner v10+). Device-local
   * and per vault, like the token: it is the id the runner looks up, never a
   * path. Empty until a pairing file or a result tells us.
   */
  profileId: string;
  /** Manually pinned protected paths (device-local). */
  protectedPaths: string[];
  /** Last known sparse-exclusion paths derived from git (refreshed on every status). */
  derivedProtectedPaths: string[];
  /** Merge derived sparse exclusions into the protected set (default on). */
  autoProtectSparse: boolean;
  opTimeoutSeconds: number;
  autoPullOnOpen: boolean;
  autoSyncOnClose: boolean;
  periodicSyncMinutes: number;
  minAutoSyncIntervalMinutes: number;
  wifiOnly: boolean;
  skipOnLowBattery: boolean;
  /** URI template for the companion-intent transport; "{id}" is replaced by the request id. */
  companionUriTemplate: string;
  /** Show a result window when an operation SUCCEEDS (failures are always shown). */
  showSuccessModals: boolean;
  /** Where short informational messages go. */
  notificationMode: "notice" | "status-only" | "log-only";
  /** Suppress the obsidian-git incompatibility warning on this device. */
  suppressObsidianGitWarning: boolean;
  /** File context menu: show the .gitignore add/remove entries. */
  menuGitignore: boolean;
  /** File context menu: show the sparse hide/show entries. */
  menuSparse: boolean;
  /** File context menu: show the .git/info/exclude add/remove entries. */
  menuExclude: boolean;
  /**
   * Epoch ms of the last "you still have an old repository set aside" reminder.
   * Device-local: the copy sits on THIS device's disk, and so does the decision
   * about it.
   */
  previousRepoRemindedAt: number;
  /** Set-aside repositories the user asked not to be reminded about again. */
  previousRepoDismissed: string[];
  /**
   * Auto-refresh status this often (seconds) while the status panel is open.
   * 0 = off. Device-local: every refresh wakes Termux, so this is a per-device
   * battery decision, never synced.
   */
  statusRefreshSeconds: number;
  /**
   * Budget for one diff, in KB. Device-local: it trades detail for how long the
   * pane takes to build, and that is a property of the phone, not of the vault.
   *
   * The runner keeps whole hunks within the budget and reports how many it had
   * to leave out, so the pane can offer to fetch the rest once. Measured at
   * roughly 12 DOM nodes per diff line, which is what actually decides whether
   * a diff feels instant or not.
   */
  diffLimitKb: number;
}

/** Selectable budgets, in KB. The default is deliberately modest. */
export const DIFF_LIMIT_CHOICES_KB = [50, 100, 200, 500, 1024] as const;
export const DEFAULT_DIFF_LIMIT_KB = 100;
/**
 * Ceiling for a ONE-OFF override, when the user asks to see a diff the setting
 * would cut. Past this the result writer truncates the field mid-line, which
 * would undo hunk-aligned cutting.
 */
export const DIFF_LIMIT_ABSOLUTE_MAX_KB = 4096;

export const CURRENT_SCHEMA_VERSION = 1;

export const DEFAULT_DEVICE_SETTINGS: DeviceLocalSettings = {
  schemaVersion: CURRENT_SCHEMA_VERSION,
  enabledOnThisDevice: false,
  termuxIntegrationEnabled: false,
  repoPathHint: "",
  authToken: "",
  profileId: "",
  protectedPaths: [...DEFAULT_PROTECTED_PATHS],
  derivedProtectedPaths: [],
  autoProtectSparse: true,
  opTimeoutSeconds: DEFAULT_TIMEOUT_SECONDS,
  autoPullOnOpen: false,
  autoSyncOnClose: false,
  periodicSyncMinutes: 0,
  minAutoSyncIntervalMinutes: 15,
  wifiOnly: false,
  skipOnLowBattery: false,
  companionUriTemplate: "nativegitbridge://run?id={id}",
  showSuccessModals: false,
  notificationMode: "notice",
  suppressObsidianGitWarning: false,
  menuGitignore: true,
  menuSparse: true,
  menuExclude: true,
  statusRefreshSeconds: 0,
  diffLimitKb: DEFAULT_DIFF_LIMIT_KB,
  previousRepoRemindedAt: 0,
  previousRepoDismissed: [],
};

/** Minimal localStorage-compatible backend, injectable for tests. */
export interface KeyValueBackend {
  getItem(key: string): string | null;
  setItem(key: string, value: string): void;
  removeItem(key: string): void;
}

/**
 * Device-local settings store.
 *
 * Backed by localStorage (per Obsidian installation, never synced through the
 * vault) and scoped by vault identity, so several vaults on one device do not
 * collide. Falls back to a volatile in-memory map when storage is unavailable
 * or cleared, and reports that through `isVolatile` (surfaced in diagnostics).
 */
export class DeviceLocalSettingsStore {
  private memory = new Map<string, string>();
  private volatile = false;

  constructor(
    private backend: KeyValueBackend | null,
    private scopeId: string
  ) {
    if (!backend) this.volatile = true;
  }

  get isVolatile(): boolean {
    return this.volatile;
  }

  private key(suffix = "settings"): string {
    return `${STORAGE_PREFIX}:${this.scopeId}:${suffix}`;
  }

  private rawGet(key: string): string | null {
    if (!this.volatile && this.backend) {
      try {
        return this.backend.getItem(key);
      } catch {
        this.volatile = true;
      }
    }
    return this.memory.get(key) ?? null;
  }

  private rawSet(key: string, value: string): void {
    if (!this.volatile && this.backend) {
      try {
        this.backend.setItem(key, value);
        return;
      } catch {
        this.volatile = true;
      }
    }
    this.memory.set(key, value);
  }

  private rawRemove(key: string): void {
    if (!this.volatile && this.backend) {
      try {
        this.backend.removeItem(key);
      } catch {
        this.volatile = true;
      }
    }
    this.memory.delete(key);
  }

  /** Read settings, merging defaults and migrating older schemas. */
  read(): DeviceLocalSettings {
    const raw = this.rawGet(this.key());
    if (raw === null) return freshDefaults();
    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch {
      // Corrupted storage: recover gracefully with defaults; quarantine the
      // corrupt blob for diagnostics instead of losing it silently.
      this.rawSet(this.key("corrupt"), raw);
      return freshDefaults();
    }
    return this.migrate(parsed);
  }

  /** Shallow-merge a patch and persist; returns the new settings. */
  write(patch: Partial<DeviceLocalSettings>): DeviceLocalSettings {
    const next = { ...this.read(), ...patch, schemaVersion: CURRENT_SCHEMA_VERSION };
    this.rawSet(this.key(), JSON.stringify(next));
    return next;
  }

  reset(): void {
    this.rawRemove(this.key());
  }

  /** Migration entry point; extend per schema bump. */
  migrate(parsed: unknown): DeviceLocalSettings {
    const obj = (typeof parsed === "object" && parsed !== null ? parsed : {}) as Record<string, unknown>;
    const merged: DeviceLocalSettings = {
      ...freshDefaults(),
      ...pickKnown(obj),
      schemaVersion: CURRENT_SCHEMA_VERSION,
    };
    if (!Array.isArray(merged.protectedPaths) || merged.protectedPaths.some((p) => typeof p !== "string")) {
      merged.protectedPaths = [...DEFAULT_PROTECTED_PATHS];
    }
    if (
      !Array.isArray(merged.derivedProtectedPaths) ||
      merged.derivedProtectedPaths.some((p) => typeof p !== "string")
    ) {
      merged.derivedProtectedPaths = [];
    }
    if (
      !Array.isArray(merged.previousRepoDismissed) ||
      merged.previousRepoDismissed.some((p) => typeof p !== "string")
    ) {
      merged.previousRepoDismissed = [];
    }
    return merged;
  }

  /** Generic scoped value access for auxiliary device-local state (log, operation markers). */
  getValue(suffix: string): string | null {
    return this.rawGet(this.key(suffix));
  }

  setValue(suffix: string, value: string): void {
    this.rawSet(this.key(suffix), value);
  }

  removeValue(suffix: string): void {
    this.rawRemove(this.key(suffix));
  }
}

function freshDefaults(): DeviceLocalSettings {
  return { ...DEFAULT_DEVICE_SETTINGS, protectedPaths: [...DEFAULT_DEVICE_SETTINGS.protectedPaths] };
}

function pickKnown(obj: Record<string, unknown>): Partial<DeviceLocalSettings> {
  const out: Record<string, unknown> = {};
  for (const k of Object.keys(DEFAULT_DEVICE_SETTINGS) as (keyof DeviceLocalSettings)[]) {
    const defVal = (DEFAULT_DEVICE_SETTINGS as unknown as Record<string, unknown>)[k];
    if (k in obj && typeof obj[k] === typeof defVal && Array.isArray(obj[k]) === Array.isArray(defVal)) {
      out[k] = obj[k];
    }
  }
  return out;
}

/** Generate a URL-safe random token (used if the user asks the plugin to create one). */
export function generateToken(bytes = 24): string {
  const arr = new Uint8Array(bytes);
  // activeWindow is Obsidian's current-window global (popout-safe); in a
  // non-browser context (tests) it is absent, and Math.random is the fallback.
  const c = typeof activeWindow !== "undefined" ? activeWindow.crypto : undefined;
  if (c?.getRandomValues) c.getRandomValues(arr);
  else for (let i = 0; i < arr.length; i++) arr[i] = Math.floor(Math.random() * 256);
  let s = "";
  const alphabet = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
  for (const b of arr) s += alphabet[b % alphabet.length];
  return s;
}
