import { STORAGE_PREFIX, DEFAULT_PROTECTED_PATHS, DEFAULT_TIMEOUT_SECONDS } from "../constants";
import {
  DEFAULT_AUTO_COMMIT_TEMPLATE,
  DEFAULT_SYNC_ON_CLOSE_TEMPLATE,
  DEFAULT_SYNC_TEMPLATE,
} from "../git/commitMessage";

export interface DeviceLocalSettings {
  schemaVersion: number;
  /** Master switch for this device; never synced through the vault. */
  enabledOnThisDevice: boolean;
  termuxIntegrationEnabled: boolean;
  /** Informational hint of the repo path as seen from Termux (the runner config owns the truth). */
  repoPathHint: string;
  /** Pairing token generated by the Termux installer and pasted here. */
  authToken: string;
  /**
   * Which Termux profile this vault is paired with (runner v10+). Device-local
   * and per vault, like the token: it is the id the runner looks up, never a
   * path. Empty until a pairing file or a result tells us.
   */
  profileId: string;
  /** Manually pinned protected paths (device-local). */
  protectedPaths: string[];
  /** Last known sparse-exclusion paths derived from git (refreshed on every status). */
  derivedProtectedPaths: string[];
  /** Merge derived sparse exclusions into the protected set (default on). */
  autoProtectSparse: boolean;
  opTimeoutSeconds: number;
  /**
   * What to do when Obsidian opens, if anything.
   *
   * "pull" was a boolean and is the default still, because it only brings work
   * in. "sync" also commits and pushes, which on launch means publishing edits
   * nobody has looked at yet — in a vault where opening the app already
   * rewrites `workspace-mobile.json`, that is a commit every single time. It is
   * offered because some people want exactly that, and it is not the default
   * because nobody should get it without asking.
   */
  onOpenAction: "nothing" | "pull" | "sync";
  autoSyncOnClose: boolean;
  periodicSyncMinutes: number;
  minAutoSyncIntervalMinutes: number;
  wifiOnly: boolean;
  skipOnLowBattery: boolean;
  /** URI template for the companion-intent transport; "{id}" is replaced by the request id. */
  companionUriTemplate: string;
  /** Show a result window when an operation SUCCEEDS (failures are always shown). */
  showSuccessModals: boolean;
  /** Where short informational messages go. */
  notificationMode: "notice" | "status-only" | "log-only";
  /** Suppress the obsidian-git incompatibility warning on this device. */
  suppressObsidianGitWarning: boolean;
  /** File context menu: show the .gitignore add/remove entries. */
  menuGitignore: boolean;
  /** File context menu: show the sparse hide/show entries. */
  menuSparse: boolean;
  /** File context menu: show the .git/info/exclude add/remove entries. */
  menuExclude: boolean;
  /**
   * Delete new (untracked) files outright instead of moving them to Obsidian's
   * trash. Off by default: a file git never saw is not in any history, so the
   * trash is the only way back. Device-local, because what it really decides is
   * whether `.trash` on THIS device is allowed to grow.
   */
  deleteUntrackedPermanently: boolean;
  /**
   * Rows the status panel draws per group before it offers the rest.
   * Device-local: what it buys is render time on this device, and the phone
   * that carries a few thousand untracked files is not the machine that decides
   * for the others.
   */
  rowsPerGroup: number;
  /**
   * How many recently typed commit messages the commit window remembers and
   * offers. Device-local: the list itself is this device's typing history
   * (kept in localStorage beside the other per-device state), and the cap
   * decides how much of it this device stores. 0 turns the recents off.
   */
  recentCommitMessagesMax: number;
  /**
   * The three automatic commit-message slots, one per trigger, each a plain
   * template string ({{date}} allowed). Device-local by the user's design
   * (2026-08-27): each device picks its own trigger messages out of the
   * SHARED template list, which lives in data.json.
   */
  syncOnCloseTemplate: string;
  autoCommitTemplate: string;
  syncTemplate: string;
  /**
   * Epoch ms of the last "you still have an old repository set aside" reminder.
   * Device-local: the copy sits on THIS device's disk, and so does the decision
   * about it.
   */
  previousRepoRemindedAt: number;
  /** Set-aside repositories the user asked not to be reminded about again. */
  previousRepoDismissed: string[];
  /**
   * Auto-refresh status this often (seconds) while the status panel is open.
   * 0 = off. Device-local: every refresh wakes Termux, so this is a per-device
   * battery decision, never synced.
   */
  statusRefreshSeconds: number;
  /**
   * Budget for one diff, in KB. Device-local: it trades detail for how long the
   * pane takes to build, and that is a property of the phone, not of the vault.
   *
   * The runner keeps whole hunks within the budget and reports how many it had
   * to leave out, so the pane can offer to fetch the rest once. Measured at
   * roughly 12 DOM nodes per diff line, which is what actually decides whether
   * a diff feels instant or not.
   */
  diffLimitKb: number;
  /**
   * Depth for the shallow-history toggle (runner v14). Device-local twice
   * over: the shallow boundary itself lives in this device's .git, and the
   * number trades disk for how far back the history panels can reach here.
   */
  shallowDepth: number;
  /**
   * Whether the one-time "sparse is on — partial clone would stop downloading
   * the hidden files' content" offer has been shown on this device. The offer
   * fires once; the settings toggle stays either way.
   */
  partialOfferShown: boolean;
}

/** Selectable budgets, in KB. The default is deliberately modest. */
/**
 * Offered row budgets for the status panel. 30 is the default because four
 * groups can be long at once and 4 × 30 is a panel that draws instantly; the
 * upper end is there for a small repository where seeing everything matters
 * more than the milliseconds.
 */
export const ROWS_PER_GROUP_CHOICES = [10, 20, 30, 50, 100, 250, 1000] as const;
export const DEFAULT_ROWS_PER_GROUP_SETTING = 30;
export const DIFF_LIMIT_CHOICES_KB = [50, 100, 200, 500, 1024] as const;
export const DEFAULT_DIFF_LIMIT_KB = 100;
/**
 * Ceiling for a ONE-OFF override, when the user asks to see a diff the setting
 * would cut. Past this the result writer truncates the field mid-line, which
 * would undo hunk-aligned cutting.
 */
export const DIFF_LIMIT_ABSOLUTE_MAX_KB = 4096;

export const CURRENT_SCHEMA_VERSION = 1;

export const DEFAULT_DEVICE_SETTINGS: DeviceLocalSettings = {
  schemaVersion: CURRENT_SCHEMA_VERSION,
  enabledOnThisDevice: false,
  termuxIntegrationEnabled: false,
  repoPathHint: "",
  authToken: "",
  profileId: "",
  protectedPaths: [...DEFAULT_PROTECTED_PATHS],
  derivedProtectedPaths: [],
  autoProtectSparse: true,
  opTimeoutSeconds: DEFAULT_TIMEOUT_SECONDS,
  onOpenAction: "nothing",
  autoSyncOnClose: false,
  periodicSyncMinutes: 0,
  minAutoSyncIntervalMinutes: 15,
  wifiOnly: false,
  skipOnLowBattery: false,
  companionUriTemplate: "nativegitbridge://run?id={id}",
  showSuccessModals: false,
  notificationMode: "notice",
  suppressObsidianGitWarning: false,
  menuGitignore: true,
  menuSparse: true,
  menuExclude: true,
  deleteUntrackedPermanently: false,
  rowsPerGroup: DEFAULT_ROWS_PER_GROUP_SETTING,
  recentCommitMessagesMax: 10,
  syncOnCloseTemplate: DEFAULT_SYNC_ON_CLOSE_TEMPLATE,
  autoCommitTemplate: DEFAULT_AUTO_COMMIT_TEMPLATE,
  syncTemplate: DEFAULT_SYNC_TEMPLATE,
  statusRefreshSeconds: 0,
  diffLimitKb: DEFAULT_DIFF_LIMIT_KB,
  previousRepoRemindedAt: 0,
  previousRepoDismissed: [],
  shallowDepth: 100,
  partialOfferShown: false,
};

/** Minimal localStorage-compatible backend, injectable for tests. */
export interface KeyValueBackend {
  getItem(key: string): string | null;
  setItem(key: string, value: string): void;
  removeItem(key: string): void;
}

/**
 * Device-local settings store.
 *
 * Backed by localStorage (per Obsidian installation, never synced through the
 * vault) and scoped by vault identity, so several vaults on one device do not
 * collide. Falls back to a volatile in-memory map when storage is unavailable
 * or cleared, and reports that through `isVolatile` (surfaced in diagnostics).
 */
export class DeviceLocalSettingsStore {
  private memory = new Map<string, string>();
  private volatile = false;

  constructor(
    private backend: KeyValueBackend | null,
    private scopeId: string
  ) {
    if (!backend) this.volatile = true;
  }

  get isVolatile(): boolean {
    return this.volatile;
  }

  private key(suffix = "settings"): string {
    return `${STORAGE_PREFIX}:${this.scopeId}:${suffix}`;
  }

  private rawGet(key: string): string | null {
    if (!this.volatile && this.backend) {
      try {
        return this.backend.getItem(key);
      } catch {
        this.volatile = true;
      }
    }
    return this.memory.get(key) ?? null;
  }

  private rawSet(key: string, value: string): void {
    if (!this.volatile && this.backend) {
      try {
        this.backend.setItem(key, value);
        return;
      } catch {
        this.volatile = true;
      }
    }
    this.memory.set(key, value);
  }

  private rawRemove(key: string): void {
    if (!this.volatile && this.backend) {
      try {
        this.backend.removeItem(key);
      } catch {
        this.volatile = true;
      }
    }
    this.memory.delete(key);
  }

  /** Read settings, merging defaults and migrating older schemas. */
  read(): DeviceLocalSettings {
    const raw = this.rawGet(this.key());
    if (raw === null) return freshDefaults();
    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch {
      // Corrupted storage: recover gracefully with defaults; quarantine the
      // corrupt blob for diagnostics instead of losing it silently.
      this.rawSet(this.key("corrupt"), raw);
      return freshDefaults();
    }
    return this.migrate(parsed);
  }

  /** Shallow-merge a patch and persist; returns the new settings. */
  write(patch: Partial<DeviceLocalSettings>): DeviceLocalSettings {
    const next = { ...this.read(), ...patch, schemaVersion: CURRENT_SCHEMA_VERSION };
    this.rawSet(this.key(), JSON.stringify(next));
    return next;
  }

  reset(): void {
    this.rawRemove(this.key());
  }

  /** Migration entry point; extend per schema bump. */
  migrate(parsed: unknown): DeviceLocalSettings {
    const obj = (typeof parsed === "object" && parsed !== null ? parsed : {}) as Record<string, unknown>;
    const merged: DeviceLocalSettings = {
      ...freshDefaults(),
      ...pickKnown(obj),
      schemaVersion: CURRENT_SCHEMA_VERSION,
    };
    if (!Array.isArray(merged.protectedPaths) || merged.protectedPaths.some((p) => typeof p !== "string")) {
      merged.protectedPaths = [...DEFAULT_PROTECTED_PATHS];
    }
    if (
      !Array.isArray(merged.derivedProtectedPaths) ||
      merged.derivedProtectedPaths.some((p) => typeof p !== "string")
    ) {
      merged.derivedProtectedPaths = [];
    }
    if (
      !Array.isArray(merged.previousRepoDismissed) ||
      merged.previousRepoDismissed.some((p) => typeof p !== "string")
    ) {
      merged.previousRepoDismissed = [];
    }
    return merged;
  }

  /** Generic scoped value access for auxiliary device-local state (log, operation markers). */
  getValue(suffix: string): string | null {
    return this.rawGet(this.key(suffix));
  }

  setValue(suffix: string, value: string): void {
    this.rawSet(this.key(suffix), value);
  }

  removeValue(suffix: string): void {
    this.rawRemove(this.key(suffix));
  }
}

function freshDefaults(): DeviceLocalSettings {
  return { ...DEFAULT_DEVICE_SETTINGS, protectedPaths: [...DEFAULT_DEVICE_SETTINGS.protectedPaths] };
}

function pickKnown(obj: Record<string, unknown>): Partial<DeviceLocalSettings> {
  const out: Record<string, unknown> = {};
  for (const k of Object.keys(DEFAULT_DEVICE_SETTINGS) as (keyof DeviceLocalSettings)[]) {
    const defVal = (DEFAULT_DEVICE_SETTINGS as unknown as Record<string, unknown>)[k];
    if (k in obj && typeof obj[k] === typeof defVal && Array.isArray(obj[k]) === Array.isArray(defVal)) {
      out[k] = obj[k];
    }
  }
  return out;
}

/** Generate a URL-safe random token (used if the user asks the plugin to create one). */
export function generateToken(bytes = 24): string {
  const arr = new Uint8Array(bytes);
  // activeWindow is Obsidian's current-window global (popout-safe); in a
  // non-browser context (tests) it is absent, and Math.random is the fallback.
  const c = typeof activeWindow !== "undefined" ? activeWindow.crypto : undefined;
  if (c?.getRandomValues) c.getRandomValues(arr);
  else for (let i = 0; i < arr.length; i++) arr[i] = Math.floor(Math.random() * 256);
  let s = "";
  const alphabet = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
  for (const b of arr) s += alphabet[b % alphabet.length];
  return s;
}
