import { STORAGE_PREFIX, DEFAULT_PROTECTED_PATHS, DEFAULT_TIMEOUT_SECONDS } from "../constants";

export interface DeviceLocalSettings {
  schemaVersion: number;
  /** Master switch for this device; never synced through the vault. */
  enabledOnThisDevice: boolean;
  termuxIntegrationEnabled: boolean;
  /** Informational hint of the repo path as seen from Termux (the runner config owns the truth). */
  repoPathHint: string;
  /** Pairing token generated by the Termux installer and pasted here. */
  authToken: string;
  protectedPaths: string[];
  opTimeoutSeconds: number;
  autoPullOnOpen: boolean;
  autoSyncOnClose: boolean;
  periodicSyncMinutes: number;
  minAutoSyncIntervalMinutes: number;
  wifiOnly: boolean;
  skipOnLowBattery: boolean;
  /** URI template for the companion-intent transport; "{id}" is replaced by the request id. */
  companionUriTemplate: string;
  /** Suppress the obsidian-git incompatibility warning on this device. */
  suppressObsidianGitWarning: boolean;
}

export const CURRENT_SCHEMA_VERSION = 1;

export const DEFAULT_DEVICE_SETTINGS: DeviceLocalSettings = {
  schemaVersion: CURRENT_SCHEMA_VERSION,
  enabledOnThisDevice: false,
  termuxIntegrationEnabled: false,
  repoPathHint: "",
  authToken: "",
  protectedPaths: [...DEFAULT_PROTECTED_PATHS],
  opTimeoutSeconds: DEFAULT_TIMEOUT_SECONDS,
  autoPullOnOpen: false,
  autoSyncOnClose: false,
  periodicSyncMinutes: 0,
  minAutoSyncIntervalMinutes: 15,
  wifiOnly: false,
  skipOnLowBattery: false,
  companionUriTemplate: "nativegitbridge://run?id={id}",
  suppressObsidianGitWarning: false,
};

/** Minimal localStorage-compatible backend, injectable for tests. */
export interface KeyValueBackend {
  getItem(key: string): string | null;
  setItem(key: string, value: string): void;
  removeItem(key: string): void;
}

/**
 * Device-local settings store.
 *
 * Backed by localStorage (per Obsidian installation, never synced through the
 * vault) and scoped by vault identity, so several vaults on one device do not
 * collide. Falls back to a volatile in-memory map when storage is unavailable
 * or cleared, and reports that through `isVolatile` (surfaced in diagnostics).
 */
export class DeviceLocalSettingsStore {
  private memory = new Map<string, string>();
  private volatile = false;

  constructor(
    private backend: KeyValueBackend | null,
    private scopeId: string
  ) {
    if (!backend) this.volatile = true;
  }

  get isVolatile(): boolean {
    return this.volatile;
  }

  private key(suffix = "settings"): string {
    return `${STORAGE_PREFIX}:${this.scopeId}:${suffix}`;
  }

  private rawGet(key: string): string | null {
    if (!this.volatile && this.backend) {
      try {
        return this.backend.getItem(key);
      } catch {
        this.volatile = true;
      }
    }
    return this.memory.get(key) ?? null;
  }

  private rawSet(key: string, value: string): void {
    if (!this.volatile && this.backend) {
      try {
        this.backend.setItem(key, value);
        return;
      } catch {
        this.volatile = true;
      }
    }
    this.memory.set(key, value);
  }

  private rawRemove(key: string): void {
    if (!this.volatile && this.backend) {
      try {
        this.backend.removeItem(key);
      } catch {
        this.volatile = true;
      }
    }
    this.memory.delete(key);
  }

  /** Read settings, merging defaults and migrating older schemas. */
  read(): DeviceLocalSettings {
    const raw = this.rawGet(this.key());
    if (raw === null) return freshDefaults();
    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch {
      // Corrupted storage: recover gracefully with defaults; quarantine the
      // corrupt blob for diagnostics instead of losing it silently.
      this.rawSet(this.key("corrupt"), raw);
      return freshDefaults();
    }
    return this.migrate(parsed);
  }

  /** Shallow-merge a patch and persist; returns the new settings. */
  write(patch: Partial<DeviceLocalSettings>): DeviceLocalSettings {
    const next = { ...this.read(), ...patch, schemaVersion: CURRENT_SCHEMA_VERSION };
    this.rawSet(this.key(), JSON.stringify(next));
    return next;
  }

  reset(): void {
    this.rawRemove(this.key());
  }

  /** Migration entry point; extend per schema bump. */
  migrate(parsed: unknown): DeviceLocalSettings {
    const obj = (typeof parsed === "object" && parsed !== null ? parsed : {}) as Record<string, unknown>;
    const merged: DeviceLocalSettings = {
      ...freshDefaults(),
      ...pickKnown(obj),
      schemaVersion: CURRENT_SCHEMA_VERSION,
    };
    if (!Array.isArray(merged.protectedPaths) || merged.protectedPaths.some((p) => typeof p !== "string")) {
      merged.protectedPaths = [...DEFAULT_PROTECTED_PATHS];
    }
    return merged;
  }

  /** Generic scoped value access for auxiliary device-local state (log, operation markers). */
  getValue(suffix: string): string | null {
    return this.rawGet(this.key(suffix));
  }

  setValue(suffix: string, value: string): void {
    this.rawSet(this.key(suffix), value);
  }

  removeValue(suffix: string): void {
    this.rawRemove(this.key(suffix));
  }
}

function freshDefaults(): DeviceLocalSettings {
  return { ...DEFAULT_DEVICE_SETTINGS, protectedPaths: [...DEFAULT_DEVICE_SETTINGS.protectedPaths] };
}

function pickKnown(obj: Record<string, unknown>): Partial<DeviceLocalSettings> {
  const out: Record<string, unknown> = {};
  for (const k of Object.keys(DEFAULT_DEVICE_SETTINGS) as (keyof DeviceLocalSettings)[]) {
    const defVal = (DEFAULT_DEVICE_SETTINGS as unknown as Record<string, unknown>)[k];
    if (k in obj && typeof obj[k] === typeof defVal && Array.isArray(obj[k]) === Array.isArray(defVal)) {
      out[k] = obj[k];
    }
  }
  return out as Partial<DeviceLocalSettings>;
}

/** Generate a URL-safe random token (used if the user asks the plugin to create one). */
export function generateToken(bytes = 24): string {
  const arr = new Uint8Array(bytes);
  const c = (globalThis as { crypto?: Crypto }).crypto;
  if (c?.getRandomValues) c.getRandomValues(arr);
  else for (let i = 0; i < arr.length; i++) arr[i] = Math.floor(Math.random() * 256);
  let s = "";
  const alphabet = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
  for (const b of arr) s += alphabet[b % alphabet.length];
  return s;
}
